import { Router } from 'express';
import {
  addHelpdeskTicketCommentController,
  addMaintenanceScheduleController,
  addMyHelpdeskTicketCommentController,
  assignHelpdeskTicketController,
  cancelHelpdeskTicketController,
  changeHelpdeskTicketWorkingStatusController,
  closeHelpdeskTicketController,
  viewHelpdeskTicketSignatureController,
  closeMaintenanceOrderController,
  confirmMyHelpdeskTicketFunctionalityController,
  createHelpdeskAssetController,
  createAssetComponentController,
  attachAssetComponentController,
  detachAssetComponentController,
  createHelpdeskCatalogItemController,
  createMaintenancePlanController,
  createHelpdeskTicketController,
  createMyHelpdeskTicketController,
  deactivateHelpdeskCatalogItemController,
  deleteHelpdeskCatalogItemController,
  deleteHelpdeskAssetController,
  evaluateHelpdeskTicketIsoRiskController,
  getHelpdeskAssetByIdController,
  getHelpdeskDashboardController,
  getHelpdeskOrgStructureController,
  getHelpdeskSummaryController,
  getHelpdeskTicketByIdController,
  getHelpdeskTicketHistoryController,
  getMyHelpdeskTicketByIdController,
  listHelpdeskCatalogAdminDataController,
  listHelpdeskAssetsController,
  getAssetReviewProgressController,
  setAssetReviewStatusController,
  listHelpdeskCatalogsController,
  listHelpdeskTicketCatalogsController,
  listHelpdeskTicketsController,
  getHelpdeskTicketStatsController,
  listMyHelpdeskAssetsController,
  listMyHelpdeskTicketsController,
  listMaintenanceCatalogsController,
  listMaintenanceOrdersController,
  listMaintenancePlansController,
  rescheduleMaintenanceOrderController,
  releaseHelpdeskTicketTechnicallyController,
  setAreaResponsiblesController,
  setUnitAreasController,
  solveHelpdeskTicketController,
  startMaintenanceOrderController,
  updateHelpdeskAssetController,
  updateHelpdeskCatalogItemController,
  updateMaintenancePlanController,
  updateHelpdeskTicketController,
  validateHelpdeskTicketReturnController,
} from '../controllers/helpdesk.controller';
import { requirePermission, verifyToken } from '../middlewares/auth.middleware';
import { validate } from '../middlewares/validate.middleware';
import {
  helpdeskAssetSchema,
  assetComponentSchema,
  assetComponentAttachSchema,
  helpdeskCatalogItemSchema,
  helpdeskTicketCommentSchema,
  helpdeskTicketIsoRiskSchema,
  helpdeskTicketSchema,
  helpdeskTicketSolveSchema,
  helpdeskTicketTechnicalReleaseSchema,
  helpdeskTicketValidateReturnSchema,
  helpdeskTicketAssignSchema,
  helpdeskTicketStatusChangeSchema,
  helpdeskTicketCloseSchema,
  helpdeskTicketCancelSchema,
  helpdeskTicketConfirmFunctionalitySchema,
  maintenanceOrderCloseSchema,
  maintenanceOrderRescheduleSchema,
  maintenancePlanSchema,
  calibrationOrderCloseSchema,
  calibrationOrderRescheduleSchema,
  calibrationPlanSchema,
  scheduleDatesSchema,
  lifecycleEventSchema,
  unitAreasSchema,
  areaResponsiblesSchema,
  handoverSchema,
  handoverSignSchema,
  handoverVoidSchema,
  assetMovementSchema,
} from '../schemas/helpdesk.schema';
import {
  createLifecycleEventController,
  getAssetExpedientController,
  getLifecycleEventDetailController,
  listAssetLifecycleEventsController,
  updateLifecycleEventController,
} from '../controllers/helpdesk-lifecycle.controller';
import {
  addCalibrationScheduleController,
  closeCalibrationOrderController,
  createCalibrationPlanController,
  listCalibrationCatalogsController,
  listCalibrationOrdersController,
  listCalibrationPlansController,
  rescheduleCalibrationOrderController,
  startCalibrationOrderController,
  updateCalibrationPlanController,
} from '../controllers/helpdesk-calibration.controller';
import {
  listAssetDocumentsController,
  uploadAssetDocumentController,
  viewAssetDocumentController,
} from '../controllers/helpdesk-asset-document.controller';
import {
  listTicketDocumentsController,
  uploadTicketDocumentController,
  viewTicketDocumentController,
} from '../controllers/helpdesk-ticket-document.controller';
import {
  createHandoverController,
  deleteHandoverController,
  getHandoverByIdController,
  listHandoverPendingAssetsController,
  listHandoversController,
  signHandoverController,
  updateHandoverController,
  viewHandoverActaController,
  voidHandoverController,
} from '../controllers/helpdesk-handover.controller';
import {
  createAssetMovementController,
  listAssetMovementsController,
  viewMovementSignatureController,
} from '../controllers/helpdesk-asset-movement.controller';
import { upload, uploadTicketDocument } from '../middlewares/upload.middleware';

const router = Router();

router.use(verifyToken);

router.get(
  '/summary',
  requirePermission('HELPDESK.DASHBOARD.READ'),
  getHelpdeskSummaryController,
);
router.get(
  '/dashboard',
  requirePermission('HELPDESK.DASHBOARD.READ'),
  getHelpdeskDashboardController,
);
router.get(
  '/me/assets',
  requirePermission('HELPDESK.SELF.ASSETS'),
  listMyHelpdeskAssetsController,
);
router.get(
  '/me/tickets',
  requirePermission('HELPDESK.SELF.TICKETS'),
  listMyHelpdeskTicketsController,
);
router.get(
  '/me/tickets/:id',
  requirePermission('HELPDESK.SELF.TICKETS'),
  getMyHelpdeskTicketByIdController,
);
router.post(
  '/me/tickets',
  requirePermission('HELPDESK.SELF.TICKETS'),
  validate(helpdeskTicketSchema),
  createMyHelpdeskTicketController,
);
router.post(
  '/me/tickets/:id/comments',
  requirePermission('HELPDESK.SELF.TICKETS'),
  validate(helpdeskTicketCommentSchema),
  addMyHelpdeskTicketCommentController,
);
router.post(
  '/me/tickets/:id/confirm-functionality',
  requirePermission('HELPDESK.SELF.TICKETS'),
  validate(helpdeskTicketConfirmFunctionalitySchema),
  confirmMyHelpdeskTicketFunctionalityController,
);
router.get(
  '/catalogs',
  requirePermission('HELPDESK.CATALOGS.READ'),
  listHelpdeskCatalogsController,
);
router.get(
  '/ticket-catalogs',
  requirePermission('HELPDESK.CATALOGS.READ'),
  listHelpdeskTicketCatalogsController,
);
router.get(
  '/maintenance-catalogs',
  requirePermission('HELPDESK.CATALOGS.READ'),
  listMaintenanceCatalogsController,
);
router.get(
  '/catalog-admin',
  requirePermission('HELPDESK.CATALOGS.MANAGE'),
  listHelpdeskCatalogAdminDataController,
);
router.post(
  '/catalog-admin/:catalogKey',
  requirePermission('HELPDESK.CATALOGS.MANAGE'),
  validate(helpdeskCatalogItemSchema),
  createHelpdeskCatalogItemController,
);
router.patch(
  '/catalog-admin/:catalogKey/:id',
  requirePermission('HELPDESK.CATALOGS.MANAGE'),
  validate(helpdeskCatalogItemSchema),
  updateHelpdeskCatalogItemController,
);
router.post(
  '/catalog-admin/:catalogKey/:id/deactivate',
  requirePermission('HELPDESK.CATALOGS.MANAGE'),
  deactivateHelpdeskCatalogItemController,
);
router.delete(
  '/catalog-admin/:catalogKey/:id',
  requirePermission('HELPDESK.CATALOGS.MANAGE'),
  deleteHelpdeskCatalogItemController,
);

// --- Estructura organizacional (Unidad <-> Area <-> Responsables) ---
router.get(
  '/org-structure',
  requirePermission('HELPDESK.ORG.READ'),
  getHelpdeskOrgStructureController,
);
router.put(
  '/units/:unitId/areas',
  requirePermission('HELPDESK.ORG.MANAGE'),
  validate(unitAreasSchema),
  setUnitAreasController,
);
router.put(
  '/areas/:areaId/responsibles',
  requirePermission('HELPDESK.ORG.MANAGE'),
  validate(areaResponsiblesSchema),
  setAreaResponsiblesController,
);

// --- Acta de entrega-recepcion de activos (ISO 15189:2022) ---
// Las rutas literales van antes de '/handovers/:id' para no capturarlas como :id.
router.get(
  '/handovers/pending-assets',
  requirePermission('HELPDESK.HANDOVERS.READ'),
  listHandoverPendingAssetsController,
);
router.get(
  '/handovers',
  requirePermission('HELPDESK.HANDOVERS.READ'),
  listHandoversController,
);
router.post(
  '/handovers',
  requirePermission('HELPDESK.HANDOVERS.WRITE'),
  validate(handoverSchema),
  createHandoverController,
);
router.get(
  '/handovers/:id/acta',
  requirePermission('HELPDESK.HANDOVERS.READ'),
  viewHandoverActaController,
);
router.get(
  '/handovers/:id',
  requirePermission('HELPDESK.HANDOVERS.READ'),
  getHandoverByIdController,
);
router.patch(
  '/handovers/:id',
  requirePermission('HELPDESK.HANDOVERS.WRITE'),
  validate(handoverSchema),
  updateHandoverController,
);
router.post(
  '/handovers/:id/sign',
  requirePermission('HELPDESK.HANDOVERS.WRITE'),
  validate(handoverSignSchema),
  signHandoverController,
);
router.post(
  '/handovers/:id/void',
  requirePermission('HELPDESK.HANDOVERS.WRITE'),
  validate(handoverVoidSchema),
  voidHandoverController,
);
router.delete(
  '/handovers/:id',
  requirePermission('HELPDESK.HANDOVERS.WRITE'),
  deleteHandoverController,
);

// --- Movimientos del activo (cambio de unidad/area/categoria/responsable) ---
router.get(
  '/movements',
  requirePermission('HELPDESK.MOVEMENTS.READ'),
  listAssetMovementsController,
);
router.post(
  '/movements',
  requirePermission('HELPDESK.MOVEMENTS.WRITE'),
  validate(assetMovementSchema),
  createAssetMovementController,
);
router.get(
  '/movements/:id/signature',
  requirePermission('HELPDESK.MOVEMENTS.READ'),
  viewMovementSignatureController,
);
router.get(
  '/maintenance/plans',
  requirePermission('HELPDESK.MAINTENANCE.READ'),
  listMaintenancePlansController,
);
router.get(
  '/maintenance/orders',
  requirePermission('HELPDESK.MAINTENANCE.READ'),
  listMaintenanceOrdersController,
);
router.post(
  '/maintenance/plans',
  requirePermission('HELPDESK.MAINTENANCE.WRITE'),
  validate(maintenancePlanSchema),
  createMaintenancePlanController,
);
router.patch(
  '/maintenance/plans/:id',
  requirePermission('HELPDESK.MAINTENANCE.WRITE'),
  validate(maintenancePlanSchema),
  updateMaintenancePlanController,
);
router.post(
  '/maintenance/orders/:id/start',
  requirePermission('HELPDESK.MAINTENANCE.WRITE'),
  startMaintenanceOrderController,
);
router.post(
  '/maintenance/orders/:id/reschedule',
  requirePermission('HELPDESK.MAINTENANCE.WRITE'),
  validate(maintenanceOrderRescheduleSchema),
  rescheduleMaintenanceOrderController,
);
router.post(
  '/maintenance/orders/:id/close',
  requirePermission('HELPDESK.MAINTENANCE.WRITE'),
  validate(maintenanceOrderCloseSchema),
  closeMaintenanceOrderController,
);
router.post(
  '/maintenance/plans/:id/schedule',
  requirePermission('HELPDESK.MAINTENANCE.WRITE'),
  validate(scheduleDatesSchema),
  addMaintenanceScheduleController,
);

// --- Calibracion (ISO 15189:2022, control metrologico 6.5) ---
router.get(
  '/calibration-catalogs',
  requirePermission('HELPDESK.CATALOGS.READ'),
  listCalibrationCatalogsController,
);
router.get(
  '/calibration/plans',
  requirePermission('HELPDESK.CALIBRATION.READ'),
  listCalibrationPlansController,
);
router.get(
  '/calibration/orders',
  requirePermission('HELPDESK.CALIBRATION.READ'),
  listCalibrationOrdersController,
);
router.post(
  '/calibration/plans',
  requirePermission('HELPDESK.CALIBRATION.WRITE'),
  validate(calibrationPlanSchema),
  createCalibrationPlanController,
);
router.patch(
  '/calibration/plans/:id',
  requirePermission('HELPDESK.CALIBRATION.WRITE'),
  validate(calibrationPlanSchema),
  updateCalibrationPlanController,
);
router.post(
  '/calibration/orders/:id/start',
  requirePermission('HELPDESK.CALIBRATION.WRITE'),
  startCalibrationOrderController,
);
router.post(
  '/calibration/orders/:id/reschedule',
  requirePermission('HELPDESK.CALIBRATION.WRITE'),
  validate(calibrationOrderRescheduleSchema),
  rescheduleCalibrationOrderController,
);
router.post(
  '/calibration/orders/:id/close',
  requirePermission('HELPDESK.CALIBRATION.WRITE'),
  validate(calibrationOrderCloseSchema),
  closeCalibrationOrderController,
);
router.post(
  '/calibration/plans/:id/schedule',
  requirePermission('HELPDESK.CALIBRATION.WRITE'),
  validate(scheduleDatesSchema),
  addCalibrationScheduleController,
);
router.get(
  '/tickets',
  requirePermission('HELPDESK.TICKETS.READ'),
  listHelpdeskTicketsController,
);
router.get(
  '/tickets/summary',
  requirePermission('HELPDESK.TICKETS.READ'),
  getHelpdeskTicketStatsController,
);
router.get(
  '/tickets/:id',
  requirePermission('HELPDESK.TICKETS.READ'),
  getHelpdeskTicketByIdController,
);
router.get(
  '/tickets/:id/history',
  requirePermission('HELPDESK.TICKETS.READ'),
  getHelpdeskTicketHistoryController,
);
router.post(
  '/tickets',
  requirePermission('HELPDESK.TICKETS.WRITE'),
  validate(helpdeskTicketSchema),
  createHelpdeskTicketController,
);
router.patch(
  '/tickets/:id',
  requirePermission('HELPDESK.TICKETS.WRITE'),
  validate(helpdeskTicketSchema),
  updateHelpdeskTicketController,
);
router.post(
  '/tickets/:id/comments',
  requirePermission('HELPDESK.TICKETS.WRITE'),
  validate(helpdeskTicketCommentSchema),
  addHelpdeskTicketCommentController,
);
router.post(
  '/tickets/:id/assign',
  requirePermission('HELPDESK.TICKETS.ASSIGN'),
  validate(helpdeskTicketAssignSchema),
  assignHelpdeskTicketController,
);
router.post(
  '/tickets/:id/status',
  requirePermission('HELPDESK.TICKETS.ASSIGN'),
  validate(helpdeskTicketStatusChangeSchema),
  changeHelpdeskTicketWorkingStatusController,
);
router.post(
  '/tickets/:id/iso-risk',
  requirePermission('HELPDESK.TICKETS.ISO_RISK'),
  validate(helpdeskTicketIsoRiskSchema),
  evaluateHelpdeskTicketIsoRiskController,
);
router.post(
  '/tickets/:id/technical-release',
  requirePermission('HELPDESK.TICKETS.TECHNICAL_RELEASE'),
  validate(helpdeskTicketTechnicalReleaseSchema),
  releaseHelpdeskTicketTechnicallyController,
);
router.post(
  '/tickets/:id/solve',
  requirePermission('HELPDESK.TICKETS.SOLVE'),
  validate(helpdeskTicketSolveSchema),
  solveHelpdeskTicketController,
);
router.post(
  '/tickets/:id/validate-return',
  requirePermission('HELPDESK.TICKETS.VALIDATE_RETURN'),
  validate(helpdeskTicketValidateReturnSchema),
  validateHelpdeskTicketReturnController,
);
router.get(
  '/tickets/:id/signature',
  requirePermission('HELPDESK.TICKETS.READ'),
  viewHelpdeskTicketSignatureController,
);
router.post(
  '/tickets/:id/close',
  requirePermission('HELPDESK.TICKETS.CLOSE'),
  validate(helpdeskTicketCloseSchema),
  closeHelpdeskTicketController,
);
router.post(
  '/tickets/:id/cancel',
  requirePermission('HELPDESK.TICKETS.CLOSE'),
  validate(helpdeskTicketCancelSchema),
  cancelHelpdeskTicketController,
);
router.get(
  '/assets',
  requirePermission('HELPDESK.ASSETS.READ'),
  listHelpdeskAssetsController,
);
// Avance de la depuracion de la carga (antes de /assets/:id para no colisionar).
router.get(
  '/assets/review-progress',
  requirePermission('HELPDESK.ASSETS.READ'),
  getAssetReviewProgressController,
);
router.get(
  '/assets/:id',
  requirePermission('HELPDESK.ASSETS.READ'),
  getHelpdeskAssetByIdController,
);
router.post(
  '/assets',
  requirePermission('HELPDESK.ASSETS.WRITE'),
  validate(helpdeskAssetSchema),
  createHelpdeskAssetController,
);
router.patch(
  '/assets/:id',
  requirePermission('HELPDESK.ASSETS.WRITE'),
  validate(helpdeskAssetSchema),
  updateHelpdeskAssetController,
);
router.delete(
  '/assets/:id',
  requirePermission('HELPDESK.ASSETS.DELETE'),
  deleteHelpdeskAssetController,
);
// Revision de carga: marcar/desmarcar activo como revisado.
router.post(
  '/assets/:id/review',
  requirePermission('HELPDESK.ASSETS.WRITE'),
  setAssetReviewStatusController,
);

// --- Componentes de activo (activos compuestos) ---
router.post(
  '/assets/:id/components',
  requirePermission('HELPDESK.ASSETS.WRITE'),
  validate(assetComponentSchema),
  createAssetComponentController,
);
router.post(
  '/assets/:id/components/attach',
  requirePermission('HELPDESK.ASSETS.WRITE'),
  validate(assetComponentAttachSchema),
  attachAssetComponentController,
);
router.post(
  '/assets/:id/detach',
  requirePermission('HELPDESK.ASSETS.WRITE'),
  detachAssetComponentController,
);

// --- Ciclo de vida del equipo (ISO 15189:2022) ---
router.get(
  '/assets/:id/expedient',
  requirePermission('HELPDESK.ASSETS.READ'),
  getAssetExpedientController,
);
router.get(
  '/assets/:id/lifecycle-events',
  requirePermission('HELPDESK.ASSETS.READ'),
  listAssetLifecycleEventsController,
);
router.post(
  '/assets/:id/lifecycle-events',
  requirePermission('HELPDESK.ASSETS.WRITE'),
  validate(lifecycleEventSchema),
  createLifecycleEventController,
);
router.get(
  '/lifecycle-events/:eventId',
  requirePermission('HELPDESK.ASSETS.READ'),
  getLifecycleEventDetailController,
);
router.patch(
  '/lifecycle-events/:eventId',
  requirePermission('HELPDESK.ASSETS.WRITE'),
  validate(lifecycleEventSchema),
  updateLifecycleEventController,
);

// --- Evidencias documentales del equipo (PDF) ---
router.get(
  '/assets/:id/documents',
  requirePermission('HELPDESK.ASSETS.READ'),
  listAssetDocumentsController,
);
router.post(
  '/assets/:id/documents',
  requirePermission('HELPDESK.ASSETS.WRITE'),
  upload.single('file'),
  uploadAssetDocumentController,
);
router.get(
  '/asset-documents/:documentId/view',
  requirePermission('HELPDESK.ASSETS.READ'),
  viewAssetDocumentController,
);

// --- Evidencia documental de tickets (PDF o imagen; TCK-03) ---
router.get(
  '/tickets/:id/documents',
  requirePermission('HELPDESK.TICKETS.READ'),
  listTicketDocumentsController,
);
router.post(
  '/tickets/:id/documents',
  requirePermission('HELPDESK.TICKETS.WRITE'),
  uploadTicketDocument.single('file'),
  uploadTicketDocumentController,
);
router.get(
  '/ticket-documents/:documentId/view',
  requirePermission('HELPDESK.TICKETS.READ'),
  viewTicketDocumentController,
);

export default router;
